# 10 Days of Statistics
https://www.hackerrank.com/challenges/s10-basic-statistics

start 11 Oct 2018

## Day 0: Mean, Median, and Mode

In [1]:
N = int(input())
while (N < 10 or N > 2500):
    N = int(input())

10


In [2]:
def getinputnumbers(N, min, max):
    X = input()
    while len(X.strip().split(' ')) != N:
        print(f'input length does not equal {N}')
        X = input()
    Xi = [int(x) for x in X.strip().split()]
    for x in Xi:
        if x < min or x > max:
            print('invalid element(s)')
            getinputnumbers(N, min, max)
    return Xi

In [3]:
Xi = getinputnumbers(N, 0, 1e5)

2 5 2 1 3 8 9 10 13 78


In [4]:
def getmean(x):
    return sum(x)/len(x)

def getmedian(x):
    x.sort()
    n = len(x)
    if n % 2 == 1:  # odd: get middle value (0 1 2 [3] 4 5 6)
        return x[int((n-1)/2)]
    else:  # even: get average of middle pair (0 1 [2 3] 4 5)
        return (x[int(n/2-1)] + x[int(n/2)])/2.
    
def getmode(x):
    counts = {}
    x.sort()
    x_set = set(x)
    x_unique_sorted = sorted(list(x_set))
    for xi in x_unique_sorted:
        counts[xi] = x.count(xi)
    print(counts)
    v = list(counts.values())
    k = list(counts.keys())
    return k[v.index(max(v))]
    # return max(counts, key=counts.get)
    
def getmode2(x):
    return max(x, key = x.count)

In [5]:
sorted(set(Xi))

[1, 2, 3, 5, 8, 9, 10, 13, 78]

In [6]:
getmode(Xi)

{1: 1, 2: 2, 3: 1, 5: 1, 8: 1, 9: 1, 10: 1, 13: 1, 78: 1}


2

In [7]:
print(f'{getmean(Xi):.1f}')

13.1


In [8]:
print(f'{getmedian(Xi):.1f}')

6.5


In [9]:
print(f'{getmode(Xi)}')

{1: 1, 2: 2, 3: 1, 5: 1, 8: 1, 9: 1, 10: 1, 13: 1, 78: 1}
2


In [10]:
print(f'{getmode2(Xi)}')

2


## Day 0: Weighted Mean

In [11]:
N = int(input())

10


In [12]:
Xi = getinputnumbers(N, 1, 100)

5 2 4 2 56 2 24 13 2 7


In [13]:
wi = getinputnumbers(N, 1, 100)

1 2 5 2 1 5 2 1 5 8


In [14]:
def getWgmean(x, w):
    n = len(x)
    weighted_sum = 0
    for i in range(n):
        weighted_sum += x[i] * w[i]
    return weighted_sum / sum(w)

In [15]:
getWgmean(Xi, wi)

7.0625

## Day 1: Quartiles

In [16]:
N = int(input())
while (N < 5 or N > 50):
    N = int(input())

5


In [17]:
Xi = getinputnumbers(N, 1, 100)

23 42 12 9 7


In [18]:
def getquartiles(x):
    x.sort()
    n = len(x)
    q2 = getmedian(x)
    if n % 2 == 1:  # odd: 0 1 2 3 4
        low_half = x[:int((n-1)/2)]
        upp_half = x[int((n-1)/2)+1:]
    else:  # even: 0 1 2 3
        low_half = x[:int(n/2)]
        upp_half = x[int(n/2):]
    q1 = getmedian(low_half)
    q3 = getmedian(upp_half)
    return q1, q2, q3

In [19]:
getquartiles(Xi)

(8.0, 12, 32.5)

## Day 1: Interquartile Range

In [20]:
N = int(input())
while (N < 5 or N > 50):
    N = int(input())

10


In [21]:
Xi = getinputnumbers(N, 1, 100)

42 24 10 8 5 4 23 8 17
input length does not equal 10
42 33 44 99 77 24 19 49 50 28


In [22]:
def getinputnumbers_sum(N, min, max, summax):
    X = input()
    while len(X.strip().split(' ')) != N:
        print(f'input length does not equal {N}')
        X = input()
    Xi = [int(x) for x in X.strip().split()]
    if sum(Xi) > summax:
        getinputnumbers_sum(N, min, max, summax)
    for x in Xi:
        if x < min or x > max:
            print('invalid element(s)')
            getinputnumbers_sum(N, min, max, summax)
    return Xi

In [23]:
fi = getinputnumbers_sum(N, 0, 1000, 1000)

42 33 44 99 77 24 19 49 50 28


In [24]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [25]:
S = []
for i, x in enumerate(Xi):
    S += [x] * fi[i]

[42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,
 99,


In [26]:
q1, q2, q3 = getquartiles(S)

In [27]:
q1

42.0

In [28]:
q3

77.0

In [29]:
q3 - q1

35.0

## Day 1: Standard Deviation

In [30]:
N = int(input())
while N not in range(5, 101):
    N = int(input())

10


In [31]:
Xi = getinputnumbers(N, 1, 100000)

42 33 44 99 77 24 19 49 50 28


In [32]:
import math

def getstd(x):
    sumsq = 0.
    for xi in x:
        sumsq += (xi - getmean(x))**2
    return math.sqrt(sumsq/len(x))

In [33]:
print('{:.1f}'.format(getstd(Xi)))

23.5


## Day 2: Basic Probability
https://www.hackerrank.com/challenges/s10-mcq-1/problem

In [34]:
die_values = list(range(1, 7))
die1 = die_values
die2 = die_values
sum_atmost_9 = 0
total_cases = 0
for d1 in die1:
    for d2 in die2:
        print('sum of {} and {} = {}'.format(d1, d2, d1+d2))
        total_cases += 1
        if d1+d2 <= 9:
            sum_atmost_9 += 1
print('--- summary ---')
print('sum at most 9 = {}'.format(sum_atmost_9))
print('total cases = {}'.format(total_cases))

sum of 1 and 1 = 2
sum of 1 and 2 = 3
sum of 1 and 3 = 4
sum of 1 and 4 = 5
sum of 1 and 5 = 6
sum of 1 and 6 = 7
sum of 2 and 1 = 3
sum of 2 and 2 = 4
sum of 2 and 3 = 5
sum of 2 and 4 = 6
sum of 2 and 5 = 7
sum of 2 and 6 = 8
sum of 3 and 1 = 4
sum of 3 and 2 = 5
sum of 3 and 3 = 6
sum of 3 and 4 = 7
sum of 3 and 5 = 8
sum of 3 and 6 = 9
sum of 4 and 1 = 5
sum of 4 and 2 = 6
sum of 4 and 3 = 7
sum of 4 and 4 = 8
sum of 4 and 5 = 9
sum of 4 and 6 = 10
sum of 5 and 1 = 6
sum of 5 and 2 = 7
sum of 5 and 3 = 8
sum of 5 and 4 = 9
sum of 5 and 5 = 10
sum of 5 and 6 = 11
sum of 6 and 1 = 7
sum of 6 and 2 = 8
sum of 6 and 3 = 9
sum of 6 and 4 = 10
sum of 6 and 5 = 11
sum of 6 and 6 = 12
--- summary ---
sum at most 9 = 30
total cases = 36


## Day 2: Compound Event Probability
https://www.hackerrank.com/challenges/s10-mcq-3/problem

In [35]:
import random

In [36]:
X = ['r'] * 4 + ['b'] * 3
Y = ['r'] * 5 + ['b'] * 4
Z = ['r'] * 4 + ['b'] * 4

picks = []
picks.append(random.sample(X, 1)[0])
picks.append(random.sample(Y, 1)[0])
picks.append(random.sample(Z, 1)[0])
picks

['b', 'b', 'r']

In [37]:
possible_picks = []
picks_with_2r1b = 0
for x in X:
    for y in Y:
        for z in Z:
            possible_picks.append([x, y, z])
total_possible_picks = len(possible_picks)

for p in possible_picks:
    if p.count('r') == 2 and p.count('b') == 1:
        picks_with_2r1b += 1

print('---summary---')
print('picks with 2r 1b = {}'.format(picks_with_2r1b))
print('total possible picks = {}'.format(total_possible_picks))
print('percent = {:.2f}'.format(100. * picks_with_2r1b / total_possible_picks))

---summary---
picks with 2r 1b = 204
total possible picks = 504
percent = 40.48


In [38]:
# simplify fraction
from fractions import Fraction

In [39]:
Fraction(picks_with_2r1b, total_possible_picks)

Fraction(17, 42)

## Day 3: Drawing Marbles
https://www.hackerrank.com/challenges/s10-mcq-6/problem

In [40]:
bag = ['red'] * 3 + ['blue'] * 4
bag
random.sample(bag, 2)

['red', 'blue']

In [41]:
bag.remove('red')
bag

['red', 'red', 'blue', 'blue', 'blue', 'blue']

In [42]:
probab_blue = bag.count('blue') / len(bag)
print(probab_blue)
print(Fraction(bag.count('blue'), len(bag)))

0.6666666666666666
2/3


## Day 3: Cards of the Same Suit
https://www.hackerrank.com/challenges/s10-mcq-5/problem

In [43]:
suits = ['club', 'diamond', 'heart', 'spade']
ranks = list(range(2, 11))
ranks.extend(['J', 'Q', 'K', 'A'])
deck = []
for r in ranks:
    for s in suits:
        deck.append((r, s))
print(f'there are {len(deck)} cards.')
two_cards = random.sample(deck, 2)
two_cards

there are 52 cards.


[(6, 'spade'), (7, 'club')]

In [44]:
len([c for c in deck if c != (4, 'diamond')])

51

In [45]:
52*51

2652

In [46]:
4*13*12

624

In [47]:
possible_hands = []
samesuit_count = 0
for card1 in deck:
    #print(card1)
    remaining_deck = [c for c in deck if not (c == card1)]
    for card2 in remaining_deck:
        possible_hands.append((card1, card2))
        if (card1[1] == card2[1]):
            samesuit_count += 1

print('---summary---')
print(f'there are {len(possible_hands)} possible hands.')
print(f'there are {samesuit_count} hands with same suit.')
print(Fraction(samesuit_count, len(possible_hands)))

---summary---
there are 2652 possible hands.
there are 624 hands with same suit.
4/17


## Day 4: Binomial Distribution I
https://www.hackerrank.com/challenges/s10-binomial-distribution-1/problem

In [49]:
while True:
    ratio_bg, child_per_birth = list(map(float, input().strip().split()))
    if ratio_bg > 0.0 and child_per_birth > 0.0:
        break

1.3 1


In [50]:
prob_boy = ratio_bg / (1. + ratio_bg)
prob_grl = 1. / (1. + ratio_bg)
prob_boy, prob_grl

(0.5652173913043479, 0.4347826086956522)

In [51]:
# prob_3b3g = (6 choose 3) * (pboy)**3 * (pgrl)**3 = (6!/(3! 3!)) * (pboy)**3 * (pgrl)**3
def factorial(x):
    if x == 0:
        return 1
    else:
        ans = x
        while x > 1:
            ans = ans * (x-1)
            x -= 1
    return ans

In [52]:
factorial(4), factorial(5), factorial(2), factorial(0)

(24, 120, 2, 1)

In [53]:
def prob_bg(b, g, pb, pg):
    ans = (factorial(b + g)/(factorial(b) * factorial(g))) * (pb**b) * (pg**g)
    return ans

prob_3b3g = prob_bg(3, 3, prob_boy, prob_grl)
print('{:.3f}'.format(prob_3b3g))

0.297


In [54]:
#prob_atleast_3b = prob3b3g + prob4b2g + prob5b1g + prob6b1g
prob_atleast_3b = prob_bg(3, 3, prob_boy, prob_grl) + prob_bg(4, 2, prob_boy, prob_grl) + \
                    prob_bg(5, 1, prob_boy, prob_grl) + prob_bg(6, 0, prob_boy, prob_grl)
print('{:.3f}'.format(prob_atleast_3b))

0.769


## Day 4: Binomial Distribution II
https://www.hackerrank.com/challenges/s10-binomial-distribution-2/problem

In [58]:
while True:
    reject_pct, batch = list(map(int, input().split()))
    reject_rate = float(reject_pct/100.)
    if reject_rate <= 100. and reject_rate >= 0. and batch > 0:
        break
print('reject rate = {}'.format(reject_rate))
print('batch = {}'.format(batch))

12 10
reject rate = 0.12
batch = 10


In [59]:
def prob_binomial(n, x, px):
    ans = (factorial(n)/(factorial(x) * factorial(n-x))) * (px**x) * ((1-px)**(n-x))
    return ans

In [60]:
p_leq2 = 0
p_geq2 = 0
# 10 samples:
# no more than 2 rejects: x = 0, 1, 2
# at least 2 rejects: x = 2, 3, .., 10
for i in range(0, 3):
    p_leq2 += prob_binomial(batch, i, reject_rate)
for i in range(2, 11):
    p_geq2 += prob_binomial(batch, i, reject_rate)
print('{:.3f}'.format(p_leq2))
print('{:.3f}'.format(p_geq2))

0.891
0.342


## Day 4: Geometric Distribution I
https://www.hackerrank.com/challenges/s10-geometric-distribution-1/problem

In [61]:
while True:
    defect_num, defect_denom = list(map(int, input().split()))
    defect_rate = float(defect_num/defect_denom)
    if defect_rate > 0:
        break
        
while True:
    inspect_id = int(input())
    if inspect_id > 0:
        break

28 100
5


In [62]:
def geom_prob(n, p):
    return (1-p)**(n-1) * p

In [63]:
print('{:.3f}'.format(geom_prob(inspect_id, defect_rate)))

0.075


## Day 4: Geometric Distribution II
https://www.hackerrank.com/challenges/s10-geometric-distribution-2/problem

In [64]:
while True:
    defect_num, defect_denom = list(map(int, input().split()))
    defect_rate = float(defect_num/defect_denom)
    if defect_rate > 0:
        break
        
while True:
    inspect_id = int(input())
    if inspect_id > 0:
        break

35 100
8


In [65]:
defect_rate

0.35

In [66]:
probab = 0.
for i in range(1, inspect_id+1):
    probab += geom_prob(i, defect_rate)
print('{:.3f}'.format(probab))

0.968


## Day 5: Poisson Distribution I
https://www.hackerrank.com/challenges/s10-poisson-distribution-1/problem

In [67]:
def p_poisson(lam, k):
    return lam**k * math.exp(-lam) / factorial(k)

In [68]:
while True:
    lam = float(input())
    if lam > 0.:
        break

2.5


In [69]:
while True:
    k = int(input())
    if k > 0:
        break

8


In [70]:
print('{:.3f}'.format(p_poisson(lam, k)))

0.003


## Day 5: Poisson Distribution II
https://www.hackerrank.com/challenges/s10-poisson-distribution-2/problem

In [71]:
while True:
    lam_a, lam_b = list(map(float, input().split()))
    if lam_a > 0 and lam_b > 0.:
        break

2.3 5.6


In [72]:
def cost_a(x):
    exp_x2 = x + x**2
    return 160. + 40. * exp_x2
def cost_b(x):
    exp_x2 = x + x**2
    return 128. + 40. * exp_x2

In [73]:
# daily cost of machine A
print('{:.3f}'.format(cost_a(lam_a)))
# daily cost of machine B
print('{:.3f}'.format(cost_b(lam_b)))

463.600
1606.400


## Day 5: Normal Distribution I
https://www.hackerrank.com/challenges/s10-normal-distribution-1/problem

In [74]:
while True:
    mean, std = list(map(float, input().split()))
    if mean > 0 and std > 0:
        break

5.6 2.3


In [75]:
while True:
    x_lessthan = float(input())
    if x_lessthan > 0:
        break

4


In [76]:
while True:
    xlo, xhi = list(map(float, input().split()))
    if xlo > 0 and xhi > 0 and xlo < xhi:
        break

2 3.5


In [77]:
import math

In [78]:
# cumulative distribution function
def cdf(x, mean, std):
    return 0.5 * (1 + math.erf((x - mean) / (std * (2 ** 0.5))))

In [79]:
# Less than x_lessthan
print('{:.3f}'.format(cdf(x_lessthan, mean, std)))
# Between xlo and xhi
print('{:.3f}'.format(cdf(xhi, mean, std) - cdf(xlo, mean, std)))

0.243
0.122


## Day 5: Normal Distribution II
https://www.hackerrank.com/challenges/s10-normal-distribution-2/problem

In [80]:
while True:
    mean, std = list(map(float, input().split()))
    if mean > 0 and std > 0:
        break

5.6 2.1


In [81]:
while True:
    g_higher = float(input())
    if g_higher > 0:
        break

7


In [82]:
while True:
    g_pass = float(input())
    if g_pass > 0:
        break

4


In [83]:
# percentage of students having grade > g_higher
print('{:.2f}'.format(100. * (1. - cdf(g_higher, mean, std))))
# percentage of students having grade >= g_pass
print('{:.2f}'.format(100. * (1. - cdf(g_pass, mean, std))))
# percentage of students having grade < g_pass
print('{:.2f}'.format(100. * cdf(g_pass, mean, std)))

25.25
77.69
22.31


## Day 6: The Central Limit Theorem I
https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-1/problem

In [84]:
while True:
    max_wgt = int(input())
    if max_wgt > 0:
        break
while True:
    boxes = int(input())
    if boxes > 0:
        break
while True:
    mean_box_wgt = int(input())
    if mean_box_wgt > 0:
        break
while True:
    sd_box_wgt = int(input())
    if sd_box_wgt > 0:
        break

9000
20
450
5


In [85]:
mu = boxes * mean_box_wgt
sd = math.sqrt(boxes) * sd_box_wgt
# probability that the elevator can successfully transport all
print('{:.4f}'.format(cdf(max_wgt, mu, sd)))

0.5000


## Day 6: Central Limit Theorem II
https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-2/problem

In [90]:
while True:
    # number of tickets available
    N = int(input())
    if N > 0:
        break
while True:
    # number of students
    n = int(input())
    if n > 0:
        break
while True:
    # average ticket purchases per student
    mu = float(input())
    if mu > 0:
        break
while True:
    # standard deviation
    sd = float(input())
    if sd > 0:
        break

250
100
2.4
2


In [91]:
mu_normal = n * mu
sd_normal = math.sqrt(n) * sd
# probability that the n students can purchase N tickets
print('{:.4f}'.format(cdf(N, mu_normal, sd_normal)))

0.6915


## Day 6: The Central Limit Theorem III
https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-3/problem

In [92]:
while True:
    # sample size
    N = int(input())
    if N > 0:
        break
while True:
    # population mean
    mu = float(input())
    if mu > 0:
        break
while True:
    # population stdev
    sd = float(input())
    if sd > 0:
        break
while True:
    # fraction
    frac = float(input())
    if frac > 0:
        break
while True:
    # z-score
    z = float(input())
    if z > 0:
        break

100
500
80
.95
1.96


In [93]:
marginOfError = z * sd / math.sqrt(N);
print('{:.2f}'.format(mu - marginOfError))
print('{:.2f}'.format(mu + marginOfError))

484.32
515.68


## Day 7: Pearson Correlation Coefficient I
https://www.hackerrank.com/challenges/s10-pearson-correlation-coefficient

In [94]:
while True:
    n = int(input())
    if n in range(10, 101):
        break
    print('try again')

10


In [95]:
def getinputfloats(N, min, max):
    X = input()
    while len(X.strip().split(' ')) != N:
        print(f'input length does not equal {N}')
        X = input()
    Xi = [float(x) for x in X.strip().split()]
    for x in Xi:
        if x < min or x > max:
            print('invalid element(s)')
            getinputfloats(N, min, max)
    return Xi

In [96]:
xi = getinputfloats(n, 1, 500)

10 9.8 8 7.8 7.7 7 6 5 4 2 


In [97]:
yi = getinputfloats(n, 1, 500)

200 44 32 24 22 17 15 12 8 4


In [98]:
def pearson_coef(x, y):
    mean_x = getmean(x)
    mean_y = getmean(y)
    std_x = getstd(x)
    std_y = getstd(y)
    n = len(x)
    divider = n * std_x * std_y
    numerator = 0.
    for xi, yi in zip(x, y):
        numerator += (xi - mean_x) * (yi - mean_y)
    return numerator/divider

In [99]:
print('{:.3f}'.format(pearson_coef(xi, yi)))

0.612


## Day 7: Spearman's Rank Correlation Coefficient
https://www.hackerrank.com/challenges/s10-spearman-rank-correlation-coefficient/problem

In [100]:
while True:
    n = int(input())
    if n in range(10, 101):
        break
    print('try again')

10


In [101]:
Xi = getinputfloats(n, 1, 500)
Yi = getinputfloats(n, 1, 500)

10 9.8 8 7.8 7.7 1.7 6 5 1.4 2 
200 44 32 24 22 17 15 12 8 4


In [102]:
def getrank(vector):
    a={}
    rank=1
    for num in sorted(vector):
        if num not in a:
            a[num]=rank
            rank=rank+1
    return [a[i] for i in vector]

In [103]:
getrank(Xi)

[10, 9, 8, 7, 6, 2, 5, 4, 1, 3]

In [104]:
getrank(Yi)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [105]:
pearson_coef(Xi, Yi)

0.5791371247539927

In [106]:
import scipy.stats as stats

In [107]:
# pearson correlation coefficient and p-value
stats.pearsonr(Xi, Yi)

(0.5791371247539927, 0.07936346183545152)

In [108]:
# pearson correlation coefficient and p-value
stats.pearsonr(getrank(Xi), getrank(Yi))

(0.9030303030303031, 0.0003436121977632796)

## Day 8: Least Square Regression Line
https://www.hackerrank.com/challenges/s10-spearman-rank-correlation-coefficient/tutorial

In [109]:
n = 5
X = []
Y = []
for i in range(n):
    while True:
        xi, yi = map(int, input().strip().split())
        if xi >= 0 and yi >= 0:
            X.append(xi)
            Y.append(yi)
            break
print(X)
print(Y)

85 95
95 85
72 59
68 71
98 91
[85, 95, 72, 68, 98]
[95, 85, 59, 71, 91]


In [111]:
sum(X)

418

In [112]:
def getb(X, Y):
    n = len(X)
    sum_xy = 0
    sum_x2 = 0
    sum_y2 = 0
    for i in range(n):
        sum_xy += X[i] * Y[i]
        sum_x2 += X[i]**2
        sum_y2 += Y[i]**2
    b = ( n * sum_xy - sum(X) * sum(Y) ) / ( n * sum_x2 - (sum(X))**2 )
    return b

def geta(X, Y, b):
    return getmean(Y) - b * getmean(X)
    
b = getb(X, Y)
a = geta(X, Y, b)

print(b, a)

def ypred(x, a, b):
    return a + b*x

print('{:.3f}'.format(ypred(80, a, b)))

0.8650306748466258 7.883435582822088
77.086


## Day 8: Pearson Correlation Coefficient II
https://www.hackerrank.com/challenges/s10-mcq-7/problem

In [1]:
# b = p * (sd_y / sd_x)
# eq1: 3x + 4y + 8 = 0 --> y = -(3/4)x - 8/3 [b1 = -3/4, a1 = -8/3]
# eq2: 4x + 3y + 7 = 0 --> x = -(3/4)y - 7/4 [b2 = -3/4, a2 = -7/4]
# b1 = p * (sd_y / sd_x)
# b2 = p * (sd_x / sd_y)
# b1 * b2 = p**2
# p = sqrt(3/4 * 3/4)
# p = +/- 3/4
# since slopes (b) are negative, p = -3/4

## Day 8: Multiple Linear Regression
https://www.hackerrank.com/challenges/s10-multiple-linear-regression/problem

In [1]:
while True:
    # m = num of features, n = num of observations
    m, n = map(int, input().strip().split())
    if m > 0 and n > 0:
        break

2 7


In [2]:
X = []
Y = []
for i in range(n):
    while True:
        vals = list(map(float, input().strip().split()))
        x = vals[0:m]
        y = vals[-1]
        print(x)
        print(y)
        break

    X.append(x)
    Y.append(y)

0
0.18 0.89 109.85
[0.18, 0.89]
109.85
1
1.0 0.26 155.72
[1.0, 0.26]
155.72
2
0.92 0.11 137.66
[0.92, 0.11]
137.66
3
0.07 0.37 76.17
[0.07, 0.37]
76.17
4
0.85 0.16 139.75
[0.85, 0.16]
139.75
5
0.99 0.41 162.6
[0.99, 0.41]
162.6
6
0.87 0.47 151.77
[0.87, 0.47]
151.77


In [8]:
X

[[0.18, 0.89],
 [1.0, 0.26],
 [0.92, 0.11],
 [0.07, 0.37],
 [0.85, 0.16],
 [0.99, 0.41],
 [0.87, 0.47]]

In [9]:
Y

[109.85, 155.72, 137.66, 76.17, 139.75, 162.6, 151.77]

In [2]:
import numpy as np

In [3]:
X = np.array([[0.18, 0.89],
 [1.0, 0.26],
 [0.92, 0.11],
 [0.07, 0.37],
 [0.85, 0.16],
 [0.99, 0.41],
 [0.87, 0.47]])

In [4]:
Y = np.array([109.85, 155.72, 137.66, 76.17, 139.75, 162.6, 151.77])

In [11]:
X0 = np.ones((n, 1))
X0

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [12]:
X = np.append(X0, X, axis=1)
X

array([[1.  , 0.18, 0.89],
       [1.  , 1.  , 0.26],
       [1.  , 0.92, 0.11],
       [1.  , 0.07, 0.37],
       [1.  , 0.85, 0.16],
       [1.  , 0.99, 0.41],
       [1.  , 0.87, 0.47]])

In [13]:
B = np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), Y)
B

array([52.41149905, 90.69331739, 46.46296549])

In [17]:
queriesX = np.array([[0.49, 0.18],
[0.57, 0.83],
[0.56, 0.64],
[0.76, 0.18]])
Xtest = np.append(np.ones((queriesX.shape[0], 1)), queriesX, axis=1)
Ytest = np.matmul(Xtest, B)
Ytest

array([105.21455835, 142.67095131, 132.93605469, 129.70175405])

In [4]:
while True:
    q = int(input())
    if q in range(1, 101):
        break

4


In [6]:
queries = []
for i in range(q):
    while True:
        x = list(map(float, input().strip().split()))
        if len(x) == m:
            queries.append(x)
            break

0.49 0.18
0.57 0.83
0.56 0.64
0.76 0.18


In [7]:
queries

[[0.49, 0.18], [0.57, 0.83], [0.56, 0.64], [0.76, 0.18]]

In [10]:
import numpy as np

In [11]:
X = np.array(X)
Y = np.array(Y)

In [13]:
X.shape

(7, 2)

In [17]:
X0 = np.ones((X.shape[0], 1))
X0

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [18]:
X = np.append(X0, X, axis=1)
X

array([[1.  , 0.  , 0.18, 0.89],
       [1.  , 0.  , 1.  , 0.26],
       [1.  , 0.  , 0.92, 0.11],
       [1.  , 0.  , 0.07, 0.37],
       [1.  , 0.  , 0.85, 0.16],
       [1.  , 0.  , 0.99, 0.41],
       [1.  , 0.  , 0.87, 0.47]])